module.exports = {
	OpenLoad: require('./openload'),
	RapidVideo: require('./rapidvideo'),
	StreaMango: require('./streamango'),
	MP4Upload: require('./mp4upload'),
	YourUpload: require('./yourupload'),
	XStreamCDN: require('./xstreamcdn'),
	Vev: require('./vev'),
	PrettyFast: require('./prettyfast'),
	TrollVid: require('./trollvid'),
	ViduPlayer: require('./viduplayer'),
	VeryStream: require('./verystream'),
	GoUnlimited: require('./gounlimited'),
	IDTBox: require('./idtbox'),
	Vidoza: require('./vidoza'),
	ClipWatching: require('./clipwatching'),
	Flix555: require('./flix555'),
	VShare: require('./vshare'),
	UnlimitedPeer: require('./unlimitedpeer'),
	Megaxfer: require('./megaxfer'),
};